export const PROGRESS_UPDATE_REQUEST = "PROGRESS_UPDATE_REQUEST";
export const PROGRESS_UPDATE_SUCCESS = "PROGRESS_UPDATE_SUCCESS";
export const PROGRESS_UPDATE_FAIL = "PROGRESS_UPDATE_FAIL";

export const PROGRESS_DETAIL_REQUEST = "PROGRESS_DETAIL_REQUEST";
export const PROGRESS_DETAIL_SUCCESS = "PROGRESS_DETAIL_SUCCESS";
export const PROGRESS_DETAIL_FAIL = "PROGRESS_DETAIL_FAIL";
