export const WORD_LIST_REQUEST = "WORD_LIST_REQUEST";
export const WORD_LIST_SUCCESS = "WORD_LIST_SUCCESS";
export const WORD_LIST_FAIL = "WORD_LIST_FAIL";

export const WORD_DETAIL_REQUEST = "WORD_DETAIL_REQUEST";
export const WORD_DETAIL_SUCCESS = "WORD_DETAIL_SUCCESS";
export const WORD_DETAIL_FAIL = "WORD_DETAIL_FAIL";
